blocks:
- from: KJT
  length_km: 47.0
  line: CENTRAL
  name: KJT-KYN
  single_track: false
  speed_limit: 100
  to: KYN
- from: KJT
  length_km: 13.0
  line: CENTRAL
  name: KJT-NRL
  single_track: false
  speed_limit: 100
  to: NRL
- from: CSMT
  length_km: 8.0
  line: CENTRAL
  name: CSMT-DR
  single_track: false
  speed_limit: 100
  to: DR
- from: DR
  length_km: 9.0
  line: CENTRAL
  name: DR-CSMT
  single_track: false
  speed_limit: 100
  to: CSMT
- from: DR
  length_km: 25.0
  line: CENTRAL
  name: DR-TNA
  single_track: false
  speed_limit: 100
  to: TNA
- from: DR
  length_km: 44.0
  line: CENTRAL
  name: DR-KYN
  single_track: false
  speed_limit: 100
  to: KYN
- from: TNA
  length_km: 24.0
  line: CENTRAL
  name: TNA-DR
  single_track: false
  speed_limit: 100
  to: DR
- from: TNA
  length_km: 20.0
  line: CENTRAL
  name: TNA-KYN
  single_track: false
  speed_limit: 100
  to: KYN
- from: KYN
  length_km: 46.0
  line: CENTRAL
  name: KYN-KJT
  single_track: false
  speed_limit: 100
  to: KJT
- from: KYN
  length_km: 45.0
  line: CENTRAL
  name: KYN-DR
  single_track: false
  speed_limit: 100
  to: DR
- from: KYN
  length_km: 20.0
  line: CENTRAL
  name: KYN-TNA
  single_track: false
  speed_limit: 100
  to: TNA
- from: KYN
  length_km: 33.0
  line: CENTRAL
  name: KYN-NRL
  single_track: false
  speed_limit: 100
  to: NRL
- from: KYN
  length_km: 67.0
  line: CENTRAL
  name: KYN-KSRA
  single_track: false
  speed_limit: 100
  to: KSRA
- from: NRL
  length_km: 13.0
  line: CENTRAL
  name: NRL-KJT
  single_track: false
  speed_limit: 100
  to: KJT
- from: NRL
  length_km: 33.0
  line: CENTRAL
  name: NRL-KYN
  single_track: false
  speed_limit: 100
  to: KYN
headway_s: 120
line_type: CENTRAL
metadata:
  description: Mumbai CENTRAL Line
  extraction_date: '2025-09-28'
  line_name: CENTRAL
  source: Government of India Railway Database
stations:
- code: CSMT
  division: null
  latitude: null
  line: CENTRAL
  longitude: null
  name: CST-MUMBAI
  platforms: 18
  zone: null
- code: DR
  division: null
  latitude: null
  line: CENTRAL
  longitude: null
  name: DADAR
  platforms: 8
  zone: null
- code: TNA
  division: null
  latitude: null
  line: TRANS_HARBOUR
  longitude: null
  name: THANE
  platforms: 10
  zone: null
- code: KYN
  division: null
  latitude: null
  line: CENTRAL
  longitude: null
  name: KALYAN JN
  platforms: 8
  zone: null
- code: KSRA
  division: null
  latitude: null
  line: CENTRAL
  longitude: null
  name: KASARA
  platforms: 3
  zone: null
- code: NRL
  division: null
  latitude: null
  line: CENTRAL
  longitude: null
  name: NERAL
  platforms: 2
  zone: null
- code: KJT
  division: null
  latitude: null
  line: CENTRAL
  longitude: null
  name: KARJAT
  platforms: 3
  zone: null
total_blocks: 15
total_stations: 7
