blocks:
- from: PNVL
  length_km: 37
  name: PNVL-TNA
  single_track: true
  speed_limit: 80
  to: TNA
- from: PNVL
  length_km: 35
  name: PNVL-KYN
  single_track: true
  speed_limit: 80
  to: KYN
- from: CSMT
  length_km: 8
  name: CSMT-DR
  single_track: true
  speed_limit: 80
  to: DR
- from: DR
  length_km: 9
  name: DR-CSMT
  single_track: true
  speed_limit: 80
  to: CSMT
- from: DR
  length_km: 25
  name: DR-TNA
  single_track: true
  speed_limit: 80
  to: TNA
- from: DR
  length_km: 44
  name: DR-KYN
  single_track: true
  speed_limit: 80
  to: KYN
- from: TNA
  length_km: 37
  name: TNA-PNVL
  single_track: true
  speed_limit: 80
  to: PNVL
- from: TNA
  length_km: 24
  name: TNA-DR
  single_track: true
  speed_limit: 80
  to: DR
- from: TNA
  length_km: 20
  name: TNA-KYN
  single_track: true
  speed_limit: 80
  to: KYN
- from: TNA
  length_km: 17
  name: TNA-LTT
  single_track: true
  speed_limit: 80
  to: LTT
- from: KYN
  length_km: 35
  name: KYN-PNVL
  single_track: true
  speed_limit: 80
  to: PNVL
- from: KYN
  length_km: 45
  name: KYN-DR
  single_track: true
  speed_limit: 80
  to: DR
- from: KYN
  length_km: 20
  name: KYN-TNA
  single_track: true
  speed_limit: 80
  to: TNA
- from: KYN
  length_km: 37
  name: KYN-LTT
  single_track: true
  speed_limit: 80
  to: LTT
- from: LTT
  length_km: 17
  name: LTT-TNA
  single_track: true
  speed_limit: 80
  to: TNA
- from: LTT
  length_km: 37
  name: LTT-KYN
  single_track: true
  speed_limit: 80
  to: KYN
headway_s: 180
roadblocks:
- block_name: DR-TNA
  duration_s: 2551
  new_speed_limit: 31
  start_time_s: 473
- block_name: PNVL-TNA
  duration_s: 1155
  new_speed_limit: 38
  start_time_s: 101
stations:
- code: PNVL
  name: PANVEL
  platforms: 2
- code: TNA
  name: THANE
  platforms: 2
- code: KYN
  name: KALYAN JN
  platforms: 2
- code: CSMT
  name: CST-MUMBAI
  platforms: 2
- code: DR
  name: DADAR
  platforms: 2
- code: LTT
  name: LOKMANYA TIL
  platforms: 2
