blocks:
- from: KRMI
  length_km: 29
  name: KRMI-MAO
  single_track: true
  speed_limit: 80
  to: MAO
- from: MAO
  length_km: 33
  name: MAO-KRMI
  single_track: true
  speed_limit: 80
  to: KRMI
- from: PUNE
  length_km: 6
  name: PUNE-KK
  single_track: true
  speed_limit: 80
  to: KK
- from: PUNE
  length_km: 266
  name: PUNE-SUR
  single_track: true
  speed_limit: 80
  to: SUR
- from: MRJ
  length_km: 47
  name: MRJ-KOP
  single_track: true
  speed_limit: 80
  to: KOP
- from: KOP
  length_km: 47
  name: KOP-MRJ
  single_track: true
  speed_limit: 80
  to: MRJ
- from: AWB
  length_km: 89
  name: AWB-NSL
  single_track: true
  speed_limit: 80
  to: NSL
- from: BSL
  length_km: 398
  name: BSL-NGP
  single_track: true
  speed_limit: 80
  to: NGP
- from: UMB
  length_km: 198
  name: UMB-NDLS
  single_track: true
  speed_limit: 80
  to: NDLS
- from: UMB
  length_km: 198
  name: UMB-DLI
  single_track: true
  speed_limit: 80
  to: DLI
- from: PNBE
  length_km: 221
  name: PNBE-JSME
  single_track: true
  speed_limit: 80
  to: JSME
- from: URK
  length_km: 1301
  name: URK-PJP
  single_track: true
  speed_limit: 80
  to: PJP
- from: ASR
  length_km: 25
  name: ASR-ATT
  single_track: true
  speed_limit: 80
  to: ATT
- from: CSMT
  length_km: 8
  name: CSMT-DR
  single_track: true
  speed_limit: 80
  to: DR
- from: DR
  length_km: 9
  name: DR-CSMT
  single_track: true
  speed_limit: 80
  to: CSMT
- from: NGP
  length_km: 398
  name: NGP-BSL
  single_track: true
  speed_limit: 80
  to: BSL
- from: NGP
  length_km: 3
  name: NGP-AJNI
  single_track: true
  speed_limit: 80
  to: AJNI
- from: NGP
  length_km: 264
  name: NGP-DURG
  single_track: true
  speed_limit: 80
  to: DURG
- from: NGP
  length_km: 130
  name: NGP-G
  single_track: true
  speed_limit: 80
  to: G
- from: AJNI
  length_km: 3
  name: AJNI-NGP
  single_track: true
  speed_limit: 80
  to: NGP
- from: MAJN
  length_km: 100
  name: MAJN-PAY
  single_track: true
  speed_limit: 80
  to: PAY
- from: KK
  length_km: 6
  name: KK-PUNE
  single_track: true
  speed_limit: 80
  to: PUNE
- from: NDLS
  length_km: 198
  name: NDLS-UMB
  single_track: true
  speed_limit: 80
  to: UMB
- from: NDLS
  length_km: 457
  name: NDLS-KOTA
  single_track: true
  speed_limit: 80
  to: KOTA
- from: NDLS
  length_km: 7
  name: NDLS-NZM
  single_track: true
  speed_limit: 80
  to: NZM
- from: ATT
  length_km: 25
  name: ATT-ASR
  single_track: true
  speed_limit: 80
  to: ASR
- from: CKP
  length_km: 62
  name: CKP-TATA
  single_track: true
  speed_limit: 80
  to: TATA
- from: TATA
  length_km: 63
  name: TATA-CKP
  single_track: true
  speed_limit: 80
  to: CKP
- from: TATA
  length_km: 138
  name: TATA-KGP
  single_track: true
  speed_limit: 80
  to: KGP
- from: TATA
  length_km: 62
  name: TATA-CBSA
  single_track: true
  speed_limit: 80
  to: CBSA
- from: KGP
  length_km: 137
  name: KGP-TATA
  single_track: true
  speed_limit: 80
  to: TATA
- from: KGP
  length_km: 108
  name: KGP-SRC
  single_track: true
  speed_limit: 80
  to: SRC
- from: KGP
  length_km: 121
  name: KGP-BLS
  single_track: true
  speed_limit: 80
  to: BLS
- from: KGP
  length_km: 116
  name: KGP-HWH
  single_track: true
  speed_limit: 80
  to: HWH
- from: KGP
  length_km: 134
  name: KGP-KOAA
  single_track: true
  speed_limit: 80
  to: KOAA
- from: KGP
  length_km: 39
  name: KGP-JGM
  single_track: true
  speed_limit: 80
  to: JGM
- from: KGP
  length_km: 13
  name: KGP-MDN
  single_track: true
  speed_limit: 80
  to: MDN
- from: SRC
  length_km: 109
  name: SRC-KGP
  single_track: true
  speed_limit: 80
  to: KGP
- from: SRC
  length_km: 7
  name: SRC-HWH
  single_track: true
  speed_limit: 80
  to: HWH
- from: SRC
  length_km: 5
  name: SRC-SHM
  single_track: true
  speed_limit: 80
  to: SHM
- from: TVC
  length_km: 64
  name: TVC-QLN
  single_track: true
  speed_limit: 80
  to: QLN
- from: QLN
  length_km: 58
  name: QLN-KCVL
  single_track: true
  speed_limit: 80
  to: KCVL
- from: BZA
  length_km: 351
  name: BZA-VSKP
  single_track: true
  speed_limit: 80
  to: VSKP
- from: VSKP
  length_km: 351
  name: VSKP-BZA
  single_track: true
  speed_limit: 80
  to: BZA
- from: BLS
  length_km: 121
  name: BLS-KGP
  single_track: true
  speed_limit: 80
  to: KGP
- from: HWH
  length_km: 116
  name: HWH-KGP
  single_track: true
  speed_limit: 80
  to: KGP
- from: KNE
  length_km: 87
  name: KNE-NJP
  single_track: true
  speed_limit: 80
  to: NJP
- from: NJP
  length_km: 87
  name: NJP-KNE
  single_track: true
  speed_limit: 80
  to: KNE
- from: HYB
  length_km: 10
  name: HYB-SC
  single_track: true
  speed_limit: 80
  to: SC
- from: SC
  length_km: 10
  name: SC-HYB
  single_track: true
  speed_limit: 80
  to: HYB
- from: SC
  length_km: 132
  name: SC-KZJ
  single_track: true
  speed_limit: 80
  to: KZJ
- from: DURG
  length_km: 264
  name: DURG-NGP
  single_track: true
  speed_limit: 80
  to: NGP
- from: DURG
  length_km: 134
  name: DURG-G
  single_track: true
  speed_limit: 80
  to: G
- from: G
  length_km: 130
  name: G-NGP
  single_track: true
  speed_limit: 80
  to: NGP
- from: G
  length_km: 134
  name: G-DURG
  single_track: true
  speed_limit: 80
  to: DURG
- from: G
  length_km: 250
  name: G-BPQ
  single_track: true
  speed_limit: 80
  to: BPQ
- from: KOAA
  length_km: 134
  name: KOAA-KGP
  single_track: true
  speed_limit: 80
  to: KGP
- from: DHN
  length_km: 3
  name: DHN-KDS
  single_track: true
  speed_limit: 80
  to: KDS
- from: KDS
  length_km: 3
  name: KDS-DHN
  single_track: true
  speed_limit: 80
  to: DHN
- from: JSME
  length_km: 221
  name: JSME-PNBE
  single_track: true
  speed_limit: 80
  to: PNBE
- from: DLI
  length_km: 197
  name: DLI-UMB
  single_track: true
  speed_limit: 80
  to: UMB
- from: KOTA
  length_km: 455
  name: KOTA-NDLS
  single_track: true
  speed_limit: 80
  to: NDLS
- from: KOTA
  length_km: 447
  name: KOTA-NZM
  single_track: true
  speed_limit: 80
  to: NZM
- from: NZM
  length_km: 7
  name: NZM-NDLS
  single_track: true
  speed_limit: 80
  to: NDLS
- from: NZM
  length_km: 450
  name: NZM-KOTA
  single_track: true
  speed_limit: 80
  to: KOTA
- from: RTGH
  length_km: 43
  name: RTGH-CUR
  single_track: true
  speed_limit: 80
  to: CUR
- from: CUR
  length_km: 43
  name: CUR-RTGH
  single_track: true
  speed_limit: 80
  to: RTGH
- from: CUR
  length_km: 57
  name: CUR-SDLP
  single_track: true
  speed_limit: 80
  to: SDLP
- from: SDLP
  length_km: 57
  name: SDLP-CUR
  single_track: true
  speed_limit: 80
  to: CUR
- from: JU
  length_km: 105
  name: JU-MTD
  single_track: true
  speed_limit: 80
  to: MTD
- from: MTD
  length_km: 103
  name: MTD-JU
  single_track: true
  speed_limit: 80
  to: JU
- from: GKP
  length_km: 64
  name: GKP-BST
  single_track: true
  speed_limit: 80
  to: BST
- from: BST
  length_km: 64
  name: BST-GKP
  single_track: true
  speed_limit: 80
  to: GKP
- from: KCVL
  length_km: 58
  name: KCVL-QLN
  single_track: true
  speed_limit: 80
  to: QLN
- from: BWT
  length_km: 47
  name: BWT-WFD
  single_track: true
  speed_limit: 80
  to: WFD
- from: BWT
  length_km: 56
  name: BWT-KJM
  single_track: true
  speed_limit: 80
  to: KJM
- from: WFD
  length_km: 47
  name: WFD-BWT
  single_track: true
  speed_limit: 80
  to: BWT
- from: WFD
  length_km: 9
  name: WFD-KJM
  single_track: true
  speed_limit: 80
  to: KJM
- from: KJM
  length_km: 56
  name: KJM-BWT
  single_track: true
  speed_limit: 80
  to: BWT
- from: KJM
  length_km: 9
  name: KJM-WFD
  single_track: true
  speed_limit: 80
  to: WFD
- from: KJM
  length_km: 3
  name: KJM-BYPL
  single_track: true
  speed_limit: 80
  to: BYPL
- from: KJM
  length_km: 5
  name: KJM-BAND
  single_track: true
  speed_limit: 80
  to: BAND
- from: KJM
  length_km: 17
  name: KJM-YPR
  single_track: true
  speed_limit: 80
  to: YPR
- from: BYPL
  length_km: 3
  name: BYPL-KJM
  single_track: true
  speed_limit: 80
  to: KJM
- from: BYPL
  length_km: 2
  name: BYPL-BAND
  single_track: true
  speed_limit: 80
  to: BAND
- from: BAND
  length_km: 5
  name: BAND-KJM
  single_track: true
  speed_limit: 80
  to: KJM
- from: BAND
  length_km: 12
  name: BAND-YPR
  single_track: true
  speed_limit: 80
  to: YPR
- from: BAND
  length_km: 51
  name: BAND-HSRA
  single_track: true
  speed_limit: 80
  to: HSRA
- from: YPR
  length_km: 17
  name: YPR-KJM
  single_track: true
  speed_limit: 80
  to: KJM
- from: YPR
  length_km: 12
  name: YPR-BAND
  single_track: true
  speed_limit: 80
  to: BAND
- from: RU
  length_km: 10
  name: RU-TPTY
  single_track: true
  speed_limit: 80
  to: TPTY
- from: HSRA
  length_km: 51
  name: HSRA-BAND
  single_track: true
  speed_limit: 80
  to: BAND
- from: KIK
  length_km: 10
  name: KIK-NCR
  single_track: true
  speed_limit: 80
  to: NCR
- from: NCR
  length_km: 11
  name: NCR-KIK
  single_track: true
  speed_limit: 80
  to: KIK
- from: KZJ
  length_km: 132
  name: KZJ-SC
  single_track: true
  speed_limit: 80
  to: SC
- from: BPQ
  length_km: 250
  name: BPQ-G
  single_track: true
  speed_limit: 80
  to: G
- from: BPQ
  length_km: 11
  name: BPQ-CAF
  single_track: true
  speed_limit: 80
  to: CAF
- from: TPTY
  length_km: 9
  name: TPTY-RU
  single_track: true
  speed_limit: 80
  to: RU
- from: COA
  length_km: 5
  name: COA-CCT
  single_track: true
  speed_limit: 80
  to: CCT
- from: CCT
  length_km: 5
  name: CCT-COA
  single_track: true
  speed_limit: 80
  to: COA
- from: NSL
  length_km: 88
  name: NSL-AWB
  single_track: true
  speed_limit: 80
  to: AWB
- from: CBSA
  length_km: 62
  name: CBSA-TATA
  single_track: true
  speed_limit: 80
  to: TATA
- from: JGM
  length_km: 39
  name: JGM-KGP
  single_track: true
  speed_limit: 80
  to: KGP
- from: MDN
  length_km: 13
  name: MDN-KGP
  single_track: true
  speed_limit: 80
  to: KGP
- from: MDN
  length_km: 72
  name: MDN-VSU
  single_track: true
  speed_limit: 80
  to: VSU
- from: SHM
  length_km: 5
  name: SHM-SRC
  single_track: true
  speed_limit: 80
  to: SRC
- from: VSU
  length_km: 72
  name: VSU-MDN
  single_track: true
  speed_limit: 80
  to: MDN
- from: VSU
  length_km: 30
  name: VSU-BQA
  single_track: true
  speed_limit: 80
  to: BQA
- from: BQA
  length_km: 30
  name: BQA-VSU
  single_track: true
  speed_limit: 80
  to: VSU
- from: CAF
  length_km: 11
  name: CAF-BPQ
  single_track: true
  speed_limit: 80
  to: BPQ
- from: SUR
  length_km: 266
  name: SUR-PUNE
  single_track: true
  speed_limit: 80
  to: PUNE
headway_s: 180
roadblocks:
- block_name: DURG-G
  duration_s: 2679
  new_speed_limit: 11
  start_time_s: 1733
- block_name: CKP-TATA
  duration_s: 3084
  new_speed_limit: 21
  start_time_s: 1691
stations:
- code: KRMI
  name: KARMALI
  platforms: 2
- code: MAO
  name: MADGOAN JN.
  platforms: 2
- code: PUNE
  name: PUNE JN.
  platforms: 2
- code: KK
  name: KHADKI
  platforms: 2
- code: SUR
  name: SOLAPUR
  platforms: 2
- code: MRJ
  name: MIRAJ JN.
  platforms: 2
- code: KOP
  name: CHHATRAPATI
  platforms: 2
- code: AWB
  name: AURANGABAD
  platforms: 2
- code: NSL
  name: NAGARSOL
  platforms: 2
- code: BSL
  name: BHUSAVAL JN.
  platforms: 2
- code: NGP
  name: NAGPUR JN.(C
  platforms: 2
- code: UMB
  name: AMBALA CANTT
  platforms: 2
- code: NDLS
  name: NEW DELHI
  platforms: 2
- code: DLI
  name: DELHI JN.
  platforms: 2
- code: PNBE
  name: PATNA JN.
  platforms: 2
- code: JSME
  name: JASIDIH JN.
  platforms: 2
- code: URK
  name: URKURA
  platforms: 2
- code: PJP
  name: PANJIPARA
  platforms: 2
- code: ASR
  name: AMRITSAR JN.
  platforms: 2
- code: ATT
  name: ATARI JN
  platforms: 2
- code: CSMT
  name: CST-MUMBAI
  platforms: 2
- code: DR
  name: DADAR
  platforms: 2
- code: AJNI
  name: AJNI
  platforms: 2
- code: DURG
  name: DURG
  platforms: 2
- code: G
  name: GONDIA JN.
  platforms: 2
- code: MAJN
  name: MANGALORE JN
  platforms: 2
- code: PAY
  name: PAYYANUR
  platforms: 2
- code: KOTA
  name: KOTA
  platforms: 2
- code: NZM
  name: HAZRAT NIZAM
  platforms: 2
- code: CKP
  name: CHAKARADHARP
  platforms: 2
- code: TATA
  name: TATANAGAR JN
  platforms: 2
- code: KGP
  name: KHARAGPUR
  platforms: 2
- code: CBSA
  name: CHAIBASA
  platforms: 2
- code: SRC
  name: SANTRAGACHI
  platforms: 2
- code: BLS
  name: BALASORE
  platforms: 2
- code: HWH
  name: HOWRAH JN.
  platforms: 2
- code: KOAA
  name: KOLKATA
  platforms: 2
- code: JGM
  name: JHARGRAM
  platforms: 2
- code: MDN
  name: MIDNAPORE
  platforms: 2
- code: SHM
  name: SHALIMAR
  platforms: 2
- code: TVC
  name: TRIVANDRUM C
  platforms: 2
- code: QLN
  name: QUILON
  platforms: 2
- code: KCVL
  name: KOCHUVELI
  platforms: 2
- code: BZA
  name: VIJAYWADA JN
  platforms: 2
- code: VSKP
  name: VISAKHAPATNA
  platforms: 2
- code: KNE
  name: KISHANGANJ
  platforms: 2
- code: NJP
  name: NEW JALPAIGU
  platforms: 2
- code: HYB
  name: HYDERABAD DE
  platforms: 2
- code: SC
  name: SECUNDERABAD
  platforms: 2
- code: KZJ
  name: KAZIPET JN.
  platforms: 2
- code: BPQ
  name: BALHARSHAH
  platforms: 2
- code: DHN
  name: DHANBAD JN.
  platforms: 2
- code: KDS
  name: KUSUNDA
  platforms: 2
- code: RTGH
  name: RATANAGARH J
  platforms: 2
- code: CUR
  name: CHURU
  platforms: 2
- code: SDLP
  name: SADULPUR JN
  platforms: 2
- code: JU
  name: JODHPUR JN.
  platforms: 2
- code: MTD
  name: MERTA ROAD J
  platforms: 2
- code: GKP
  name: GORAKHPUR JN
  platforms: 2
- code: BST
  name: BASTI
  platforms: 2
- code: BWT
  name: BANGARPET JN
  platforms: 2
- code: WFD
  name: WHITE FIELD
  platforms: 2
- code: KJM
  name: KRISHNA RAJA
  platforms: 2
- code: BYPL
  name: BAIYYAPPANAH
  platforms: 2
- code: BAND
  name: BANASWADI
  platforms: 2
- code: YPR
  name: YESVANTPUR J
  platforms: 2
- code: HSRA
  name: HOSUR
  platforms: 2
- code: RU
  name: RENIGUNTA JN
  platforms: 2
- code: TPTY
  name: TIRUPATI
  platforms: 2
- code: KIK
  name: KARAIKAL
  platforms: 2
- code: NCR
  name: NAGORE
  platforms: 2
- code: CAF
  name: CHANDAFORT
  platforms: 2
- code: COA
  name: KAKINADA POR
  platforms: 2
- code: CCT
  name: KAKINADA TOW
  platforms: 2
- code: VSU
  name: BISHNUPUR
  platforms: 2
- code: BQA
  name: BANKURA
  platforms: 2
